version: '3.4'
services:
  app: &app
    build:
      context: .
      target: dev
    depends_on:
    - db
    - mail
    - cache
    env_file: .docker/app.env
    ports:
    - 3000
    volumes:
    - ./:/app
    - seed:/seed

  worker:
    <<: *app
    command: [ rake, 'jobs:work' ]
    depends_on:
    - db
    - mail
    - cache

  test:
    build:
      context: .
      target: test
    depends_on:
    - db-test
    env_file: .docker/app.env
    environment:
      RAILS_DB_NAME: hitobito_test
      RAILS_DB_HOST: db-test
    volumes:
    - ./:/app

  # Dependencies

  mail:
    build:
      context: .
      target: base
    command: [ mailcatcher, -f, --ip, '0.0.0.0' ]
    ports:
    - 1080

  cache:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]

  sphinx:
    image: macbre/sphinxsearch:3.1.1
    depends_on:
    - db
    volumes:
    - sphinx:/opt/sphinx/index
    - ./.docker/sphinx.conf:/opt/sphinx/conf/sphinx.conf:ro

  indexer:
    image: macbre/sphinxsearch:3.1.1
    command: [ indexer, --config, /opt/sphinx/conf/sphinx.conf, --all ]
    depends_on:
    - db
    volumes:
    - sphinx:/opt/sphinx/index
    - ./.docker/sphinx.conf:/opt/sphinx/conf/sphinx.conf:ro

  db:
    image: mysql:5.6
    command:
    - --sort_buffer_size=2M
    env_file: .docker/mysql.env
    volumes:
    - db:/var/lib/mysql

  db-test:
    image: mysql:5.6
    command:
    - --sort_buffer_size=2M
    env_file: .docker/mysql.env
    environment:
      MYSQL_DATABASE: hitobito_test

volumes:
  db:
  sphinx:
  seed:

